# -*- coding: utf-8 -*-
"""pro106

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XwlviVvf8lBHI_xjP_Ob-cWuc3VXRdfa
"""

from google.colab import files
data_to_load=files.upload()

import plotly.express as px 
import csv
with open("data4.csv")as csv_file:
  df=csv.DictReader(csv_file)
  fig=px.scatter(df,x="Days Present",y="Marks In Percentage")
  fig.show()

import plotly.express as px
import csv
import numpy as np
def plotfigure(data_path):
  with open(data_path)as csv_file:
    df=csv.DictReader(csv_file)
    fig=px.scatter(df,x="Days Present",y="Marks In Percentage")
    fig.show()

def getdatasource(data_path):
  marks_in_percentage=[]
  days_present=[]
  with open(data_path)as csv_file:
    csv_reader=csv.DictReader(csv_file)
    for row in csv_reader:
      marks_in_percentage.append(float(row["Marks In Percentage"]))
      days_present.append(float(row["Days Present"]))
  
  return{"x":marks_in_percentage,"y":days_present}

def findCorrelation(datasource):
  correlation=np.corrcoef(datasource["x"],datasource["y"])
  print("correlation between marks in percentage and days present: \n",correlation[0,1])

def setup():
  data_path="data4.csv"
  datasource=getdatasource(data_path)
  findCorrelation(datasource)
  plotfigure(data_path)
setup()